name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test with Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v5

    - name: Install uv and set the Python version
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Enable caching
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true

    - name: Display Python version
      run: python --version

    - name: Install the project
      run: |
        uv lock && uv sync --locked --all-extras --dev

    - name: Run tests with pytest and coverage
      run: |
        uv run pytest --cov=src/sparkenforce --cov-report=xml --cov-report=term-missing

    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        format: cobertura
        file: coverage.xml
